 language: rust
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
    - dist: xenial
      compiler: clang
    
  
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'g++-5']
 



before_script:
- export PATH="$PATH:$HOME/.cargo/bin"


before_install:

 - gem install bundler
 - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly --profile=minimal
 - export PATH="$PATH:$HOME/.cargo/bin"
 - sudo add-apt-repository ppa:beineri/opt-qt591-xenial -y
 - sudo apt-get update -qq
 - sudo apt-get install qt59base qt59websockets libgl1-mesa-dev
 - source /opt/qt59/bin/qt59-env.sh
 
script:

 - qmake -v
 - clang++ -v
 - g++-5 -v
 - qmake safecoinwallet-lite.pro CONFIG+=release -spec linux-clang
 - make CC=clang CXX=clang++ -j2
 - make distclean
 - qmake safecoinwallet-lite.pro CONFIG+=release -spec linux-g++
 - res/libsodium/buildlibsodium.sh
 - make CC=gcc-5 CXX=g++-5 -j2
 
